// This file is auto-generated by the 'new' command - do not edit this by hand!
import { default as index20221 } from './2022/1/index.js';
import { default as index20222 } from './2022/2/index.js';
import { default as index20223 } from './2022/3/index.js';
import { default as index20224 } from './2022/4/index.js';
import { default as index20225 } from './2022/5/index.js';
import { default as index20226 } from './2022/6/index.js';
import { default as index20227 } from './2022/7/index.js';
import { default as index20228 } from './2022/8/index.js';
import { default as index20229 } from './2022/9/index.js';

const days = {};
days['2022/1'] = index20221;
days['2022/2'] = index20222;
days['2022/3'] = index20223;
days['2022/4'] = index20224;
days['2022/5'] = index20225;
days['2022/6'] = index20226;
days['2022/7'] = index20227;
days['2022/8'] = index20228;
days['2022/9'] = index20229;

export default days;
