// This file is auto-generated by the 'new' command - do not edit this by hand!
import { default as index20221 } from './2022/1/index.js';
import { default as index20222 } from './2022/2/index.js';
import { default as index20223 } from './2022/3/index.js';
import { default as index20224 } from './2022/4/index.js';
import { default as index20225 } from './2022/5/index.js';
import { default as index20226 } from './2022/6/index.js';
import { default as index20227 } from './2022/7/index.js';
import { default as index20228 } from './2022/8/index.js';
import { default as index20229 } from './2022/9/index.js';
import { default as index202210 } from './2022/10/index.js';
import { default as index202211 } from './2022/11/index.js';
import { default as index202212 } from './2022/12/index.js';
import { default as index202213 } from './2022/13/index.js';

const days = {
  '2022/1': index20221,
  '2022/2': index20222,
  '2022/3': index20223,
  '2022/4': index20224,
  '2022/5': index20225,
  '2022/6': index20226,
  '2022/7': index20227,
  '2022/8': index20228,
  '2022/9': index20229,
  '2022/10': index202210,
  '2022/11': index202211,
  '2022/12': index202212,
  '2022/13': index202213
};

export default days;
